### ISSUE TITLE
[UX] - Create  a User Flow in Figma

### ISSUE THREAD

**Issue by msboffl** [qeetgroup/qmart#2]
Create and Design a User Flow for an eCommerce Application for both Buyer and Seller

Here is the Figma file link - [Figma File](https://www.figma.com/team_invite/redeem/55tuosQzDHHyH5pBXYpq2X)

**Comment by msboffl** [comment]
@Atharva1802 Do you have access to the file.?

**Comment by msboffl** [comment]
@Atharva1802 Check this link - https://www.figma.com/team_invite/redeem/55tuosQzDHHyH5pBXYpq2X

**Comment by msboffl** [comment]
Do you want to hacktoberfest count, Please follow the below points. Once you created you can do like this 

1. Fork the repository and clone it in local
2. I will Create a Design.MD file, you can update the file and raise PR. It will count

**Comment by Atharva1802** [comment]
Yeah thanks!

**Comment by Atharva1802** [comment]
I've completed my part. @msboffl Please label my PR as Hacktoberfest-accepted if you're satisfied.
Thank you

**Comment by msboffl** [comment]
@Atharva1802 It's really good bro.
